import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Navbar from "./components/navbar.js";
import { LoginProvider } from "./contexts/loginContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-lt-installed="true">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LoginProvider>
          <Navbar />
          {children}
        </LoginProvider>
      </body>
    </html>
  );
}
